swagger: "2.0"
info:
  version: "0.0.1"
  title: Watson API Wrapper
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
  - application/x-www-form-urlencoded
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /personality/help:
    # binds a127 app logic to a route
    x-swagger-router-controller: personality
    get:
      description: personality APIの概要を表示する
      # used as the method name of the controller
      operationId: personality_help
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/NormalResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /personality/insights:
    # binds a127 app logic to a route
    x-swagger-router-controller: personality
    post:
      description: テキストを元にPersonality Insightsの結果を返す
      # used as the method name of the controller
      operationId: personality_insights
      parameters:
        - name: text
          in: formData
          description: 解析するテキスト
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/PersonalityInsightsResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ResponseErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  PersonalityInsightsResponse:
    required:
      - id
      - source
      - word_count
      - word_count_message
    properties:
      id:
        type: string
      source:
        type: string
      word_count:
        type: number
      word_count_message:
        type: string
  NormalResponse:
    required:
      - name
      - version
    properties:
      name:
        type: string
      version:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  ResponseErrorResponse:
    required:
      - code
      - help
      - error
    properties:
      code:
        type: number
      help:
        type: string
      error:
        type: string